import Head from "next/head";
import React from "react";
import { FaChevronLeft, FaChevronRight } from "react-icons/fa";
import Button from "../components/Button";
import Header from "../components/Header";
import Rotator from "../components/Rotator";
import styles from "../styles/Home.module.scss";

const mock = [
  {
    title: "1",
    description:
      "While having drinks with Tibor Kalman one night, he told me, “When you make something no one hates, no one fucking loves it.” Creativity requires fucking tenacity. Most of your accomplishments will be demonstrations of tenacity, not talent. Someday is not a fucking day of the week. Be fucking bold.",
  },
  {
    title: "2",
    description:
      "While having drinks with Tibor Kalman one night, he told me, “When you make something no one hates, no one fucking loves it.” Creativity requires fucking tenacity. Most of your accomplishments will be demonstrations of tenacity, not talent. Someday is not a fucking day of the week. Be fucking bold.",
  },
  {
    title: "3",
    description:
      "While having drinks with Tibor Kalman one night, he told me, “When you make something no one hates, no one fucking loves it.” Creativity requires fucking tenacity. Most of your accomplishments will be demonstrations of tenacity, not talent. Someday is not a fucking day of the week. Be fucking bold.",
  },
  {
    title: "4",
    description:
      "While having drinks with Tibor Kalman one night, he told me, “When you make something no one hates, no one fucking loves it.” Creativity requires fucking tenacity. Most of your accomplishments will be demonstrations of tenacity, not talent. Someday is not a fucking day of the week. Be fucking bold.",
  },
];

export default function Home() {
  const [active, setActive] = React.useState<number>(0);

  const handleChange = (type: "next" | "back") => {
    switch (type) {
      case "back":
        active === 0 ? setActive(mock.length - 1) : setActive(active - 1);
        break;
      case "next":
      default:
        active === mock.length - 1 ? setActive(0) : setActive(active + 1);
        break;
    }
  };

  return (
    <div>
      <Head>
        <title>PassPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.controls}>
          <Button
            className={styles.next}
            label={<FaChevronRight size={25} />}
            onClick={() => handleChange("next")}
          />
          <Button
            className={styles.back}
            label={<FaChevronLeft size={25} />}
            onClick={() => handleChange("back")}
          />
        </div>

        <Rotator active={active} projects={mock} />
      </main>
    </div>
  );
}
