import classNames from 'classnames'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const [displyers, setDisplayers] = React.useState<number[]>([0,1,2,3])
  const [active, setActive] = React.useState<number>(0)

  return (
    <div>
      <Head>
        <title>PassPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <button className={styles.next} onClick={() => setActive(active + 1)}>Next</button>
      <div className={styles.container} style={{ transform: `translateY(${450 * 3}px) rotateZ(${active * 90}deg)` }}>
        {displyers.map((elem, index) => ( 
          <div key={elem} className={classNames(styles.displayer)}></div>
        ))}
      </div>
      </main> 
    </div>
  )
}
